databases:
  - name: travel_app_db
    plan: free
    databaseName: travel_app_db
    user: travel_app_user

services:
  - type: web
    plan: free
    name: alx_travel_app
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: travel_app_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4